### ISSUE TITLE
Parsing problem

### ISSUE THREAD

**Issue by kmonticolo** [kvaps/pve-autosnap#3]
I got an error "option doesn't allow an argument"
 when run a command from readme:
 
pve-autosnap --daily --storage=local --leave=3
parse-options: option '--storage' doesn't allow an argument
parse-options: option '--leave' doesn't allow an argument

but it passes when I run it as shown below:
pve-autosnap --daily --storage local --leave 3

**Comment by michabbs** [comment]
I think I repaired it some time ago:
https://github.com/michabbs/pve-autosnap/commit/2abccefe79a526e51ef97ce1651a0c2414752a27
